### ISSUE TITLE
BadImageFormatException on iCal.net nugget for a .net4.6 projet

### ISSUE THREAD

**Issue by StephaneG31** [dsplaisted/strongnamer#20]
I have an error using StrongNamer on a projet .net 4.6 where I want to add iCal.net
https://www.nuget.org/packages/Ical.Net/

iCal.net used .net standart, path ic packages\Ical.Net.4.0.6\lib\netstandard1.3

The error on VS 2017 (15.6.5)
`
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "StrongNamer.AddStrongName" task failed unexpectedly.
System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, StrongNameKeyPair key, StrongNamerAssemblyResolver resolver)
   at StrongNamer.AddStrongName.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FranceTelecom.Systems			
`

**Comment by Sam13** [comment]
Maybe fixed with #28?
