### ISSUE TITLE
BadImageFormatException on Autodesk.Forge NuGet for a .Net 4.7.2 project

### ISSUE THREAD

**Issue by chessar** [dsplaisted/strongnamer#24]
[Autodesk.Forge 1.2.0 NuGet package](https://www.nuget.org/packages/Autodesk.Forge/)

```csharp
The "StrongNamer.AddStrongName" task failed unexpectedly.
System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, StrongNameKeyPair key, StrongNamerAssemblyResolver resolver)
   at StrongNamer.AddStrongName.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
AutodeskConsoleApp
```

[AutodeskConsoleApp.zip](https://github.com/dsplaisted/strongnamer/files/2229043/AutodeskConsoleApp.zip)

**Comment by ugumba** [comment]
I suspect PR#28 fixed this. I have not tried with your repro.

**Comment by chessar** [comment]
Hello @ugumba ,

With StrongNamer v0.0.8 and Autodesk.Forge v1.3.0 works without errors. Thanks.
