### ISSUE TITLE
The "StrongNamer.AddStrongName" task failed unexpectedly.

### ISSUE THREAD

**Issue by Berke-Alp** [dsplaisted/strongnamer#51]
I'm getting this error when I try to build my Class Library project.

```
The "StrongNamer.AddStrongName" task failed unexpectedly.
System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName)
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, Byte[] keyBytes, StrongNamerAssemblyResolver resolver)
   at StrongNamer.AddStrongName.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FeryLib			
```

**Comment by Berke-Alp** [comment]
I'm trying to reference **Flurl**, **Flurl.Http** and **Newtonsoft.Json**
